"""empty message

Revision ID: 35becc63edb9
Revises: e281b6e5ed26
Create Date: 2023-11-04 18:40:17.290736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35becc63edb9'
down_revision = 'e281b6e5ed26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
