"""empty message

Revision ID: 90932cd71a85
Revises: 5cae6f612ef9
Create Date: 2023-11-11 00:05:40.697098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90932cd71a85'
down_revision = '5cae6f612ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
