"""empty message

Revision ID: c14e948f25eb
Revises: 7217fbe09779
Create Date: 2023-11-08 19:47:52.001561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14e948f25eb'
down_revision = '7217fbe09779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedIn', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('github')
        batch_op.drop_column('linkedIn')

    # ### end Alembic commands ###
